FROM busybox:1.36

# Create a non-root user to own the files and run our server
RUN adduser -D fileserver
USER fileserver
WORKDIR /var/http

# Run BusyBox httpd
CMD ["busybox", "httpd", "-fvvvp", "8999"]